/* Generated by cbindgen from crates/ringgrid-c. Do not edit by hand. */

#ifndef RINGGRID_H
#define RINGGRID_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * The ABI version of this library, bumped on any breaking change to the C
 * surface. Consumers compiled against a header should check it matches
 * [`ringgrid_abi_version`](crate::introspect::ringgrid_abi_version).
 */
#define RINGGRID_ABI_VERSION 1

/**
 * Result status for every fallible `ringgrid_*` call.
 *
 * `RINGGRID_STATUS_OK` (0) is success; any other value is an error and the
 * call's out-parameter is left untouched.
 */
typedef enum {
    /**
     * Success.
     */
    RINGGRID_STATUS_OK = 0,
    /**
     * A required pointer argument was NULL.
     */
    RINGGRID_STATUS_ERR_NULL_ARG = 1,
    /**
     * A JSON argument (target, config, tiers, or mapper) failed to parse.
     */
    RINGGRID_STATUS_ERR_BAD_JSON = 2,
    /**
     * Image dimensions were zero, overflowed, or the buffer did not match.
     */
    RINGGRID_STATUS_ERR_BAD_IMAGE = 3,
    /**
     * Detection failed (e.g. an unsupported target or a strict-mode gate).
     */
    RINGGRID_STATUS_ERR_DETECT = 4,
    /**
     * Serializing the result to JSON failed (should not happen in practice).
     */
    RINGGRID_STATUS_ERR_SERIALIZE = 5,
    /**
     * A heatmap accessor was called before `ringgrid_propose_with_heatmap`.
     */
    RINGGRID_STATUS_ERR_NO_HEATMAP = 6,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    RINGGRID_STATUS_ERR_PANIC = 7,
} RinggridStatus;

/**
 * Opaque, heap-owned detector handle.
 *
 * Holds the target layout, detection config, and the last proposal heatmap.
 * Create with `ringgrid_detector_new` (or a `_with_*` variant) and release
 * with `ringgrid_detector_free`. Not thread-safe: use one handle per thread,
 * or synchronize externally.
 */
typedef struct RinggridDetector RinggridDetector;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string previously written by any `ringgrid_*` function. NULL is a
 * no-op.
 *
 * # Safety
 * `s` must be NULL or a pointer written to a `char**` out-parameter by this
 * library, freed exactly once. Passing any other pointer, or freeing twice, is
 * undefined behavior.
 */
void ringgrid_string_free(char *s);

/**
 * Detect markers in an 8-bit grayscale image. Writes a `DetectionResult` JSON
 * string to `out` (owned; free with `ringgrid_string_free`).
 *
 * # Safety
 * `handle` must be a live handle; `pixels` must point to at least
 * `width * height` readable bytes; `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_detect(const RinggridDetector *handle,
                               const uint8_t *pixels,
                               uint32_t width,
                               uint32_t height,
                               char **out);

/**
 * Detect markers in an RGBA image (BT.601-converted to grayscale first).
 *
 * # Safety
 * As [`ringgrid_detect`], but `pixels` must point to `width * height * 4` bytes.
 */
RinggridStatus ringgrid_detect_rgba(const RinggridDetector *handle,
                                    const uint8_t *pixels,
                                    uint32_t width,
                                    uint32_t height,
                                    char **out);

/**
 * Detect markers (grayscale), writing `{"result": ..., "diagnostics": ...}` to
 * `out`. `diagnostics.markers` aligns 1:1 with `result.detected_markers`.
 *
 * # Safety
 * See [`ringgrid_detect`].
 */
RinggridStatus ringgrid_detect_with_diagnostics(const RinggridDetector *handle,
                                                const uint8_t *pixels,
                                                uint32_t width,
                                                uint32_t height,
                                                char **out);

/**
 * Detect markers (RGBA) with diagnostics. See
 * [`ringgrid_detect_with_diagnostics`].
 *
 * # Safety
 * See [`ringgrid_detect_rgba`].
 */
RinggridStatus ringgrid_detect_with_diagnostics_rgba(const RinggridDetector *handle,
                                                     const uint8_t *pixels,
                                                     uint32_t width,
                                                     uint32_t height,
                                                     char **out);

/**
 * Adaptive multi-tier detection (grayscale).
 *
 * # Safety
 * See [`ringgrid_detect`].
 */
RinggridStatus ringgrid_detect_adaptive(const RinggridDetector *handle,
                                        const uint8_t *pixels,
                                        uint32_t width,
                                        uint32_t height,
                                        char **out);

/**
 * Adaptive multi-tier detection (RGBA).
 *
 * # Safety
 * See [`ringgrid_detect_rgba`].
 */
RinggridStatus ringgrid_detect_adaptive_rgba(const RinggridDetector *handle,
                                             const uint8_t *pixels,
                                             uint32_t width,
                                             uint32_t height,
                                             char **out);

/**
 * Adaptive detection with a nominal marker diameter hint in pixels (grayscale).
 *
 * # Safety
 * See [`ringgrid_detect`].
 */
RinggridStatus ringgrid_detect_adaptive_with_hint(const RinggridDetector *handle,
                                                  const uint8_t *pixels,
                                                  uint32_t width,
                                                  uint32_t height,
                                                  float nominal_diameter_px,
                                                  char **out);

/**
 * Adaptive detection with a nominal marker diameter hint in pixels (RGBA).
 *
 * # Safety
 * See [`ringgrid_detect_rgba`].
 */
RinggridStatus ringgrid_detect_adaptive_with_hint_rgba(const RinggridDetector *handle,
                                                       const uint8_t *pixels,
                                                       uint32_t width,
                                                       uint32_t height,
                                                       float nominal_diameter_px,
                                                       char **out);

/**
 * Multi-scale detection with explicit tiers `{"tiers": [{"diameter_min_px":
 * .., "diameter_max_px": ..}, ...]}` (grayscale).
 *
 * # Safety
 * As [`ringgrid_detect`]; `tiers_json` must be a valid NUL-terminated C string.
 */
RinggridStatus ringgrid_detect_multiscale(const RinggridDetector *handle,
                                          const uint8_t *pixels,
                                          uint32_t width,
                                          uint32_t height,
                                          const char *tiers_json,
                                          char **out);

/**
 * Multi-scale detection with explicit tiers (RGBA).
 *
 * # Safety
 * As [`ringgrid_detect_rgba`]; `tiers_json` must be a valid NUL-terminated C string.
 */
RinggridStatus ringgrid_detect_multiscale_rgba(const RinggridDetector *handle,
                                               const uint8_t *pixels,
                                               uint32_t width,
                                               uint32_t height,
                                               const char *tiers_json,
                                               char **out);

/**
 * Two-pass detection through an external pixel mapper (grayscale).
 * `mapper_json` is a `MapperSpec` (`{"kind":"camera",...}` /
 * `{"kind":"division",...}`).
 *
 * # Safety
 * As [`ringgrid_detect`]; `mapper_json` must be a valid NUL-terminated C string.
 */
RinggridStatus ringgrid_detect_with_mapper(const RinggridDetector *handle,
                                           const uint8_t *pixels,
                                           uint32_t width,
                                           uint32_t height,
                                           const char *mapper_json,
                                           char **out);

/**
 * Two-pass detection through an external pixel mapper (RGBA).
 *
 * # Safety
 * As [`ringgrid_detect_rgba`]; `mapper_json` must be a valid NUL-terminated C string.
 */
RinggridStatus ringgrid_detect_with_mapper_rgba(const RinggridDetector *handle,
                                                const uint8_t *pixels,
                                                uint32_t width,
                                                uint32_t height,
                                                const char *mapper_json,
                                                char **out);

/**
 * Two-pass detection through an external mapper, with diagnostics (grayscale).
 *
 * # Safety
 * As [`ringgrid_detect_with_mapper`].
 */
RinggridStatus ringgrid_detect_with_mapper_diagnostics(const RinggridDetector *handle,
                                                       const uint8_t *pixels,
                                                       uint32_t width,
                                                       uint32_t height,
                                                       const char *mapper_json,
                                                       char **out);

/**
 * Two-pass detection through an external mapper, with diagnostics (RGBA).
 *
 * # Safety
 * As [`ringgrid_detect_with_mapper_rgba`].
 */
RinggridStatus ringgrid_detect_with_mapper_diagnostics_rgba(const RinggridDetector *handle,
                                                            const uint8_t *pixels,
                                                            uint32_t width,
                                                            uint32_t height,
                                                            const char *mapper_json,
                                                            char **out);

/**
 * Create a detector from a target layout JSON string (`v5`, or legacy `v4`).
 *
 * # Safety
 * `target_json` must be a valid NUL-terminated C string; `out` must point to a
 * writable handle slot.
 */
RinggridStatus ringgrid_detector_new(const char *target_json, RinggridDetector **out);

/**
 * Create a detector with an explicit min/max marker diameter (pixels).
 *
 * # Safety
 * See [`ringgrid_detector_new`].
 */
RinggridStatus ringgrid_detector_with_marker_scale(const char *target_json,
                                                   float min_px,
                                                   float max_px,
                                                   RinggridDetector **out);

/**
 * Create a detector with a nominal marker diameter hint (pixels).
 *
 * # Safety
 * See [`ringgrid_detector_new`].
 */
RinggridStatus ringgrid_detector_with_marker_diameter(const char *target_json,
                                                      float diameter_px,
                                                      RinggridDetector **out);

/**
 * Create a detector from a target plus a full config snapshot (as returned by
 * `ringgrid_detector_config_json`).
 *
 * # Safety
 * `target_json` and `config_json` must be valid NUL-terminated C strings;
 * `out` must point to a writable handle slot.
 */
RinggridStatus ringgrid_detector_with_config(const char *target_json,
                                             const char *config_json,
                                             RinggridDetector **out);

/**
 * Write the current detection config as a JSON string to `out` (owned; free
 * with `ringgrid_string_free`).
 *
 * # Safety
 * `handle` must be a live handle; `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_detector_config_json(const RinggridDetector *handle, char **out);

/**
 * Apply a partial config overlay (a JSON object with any subset of config
 * fields; stage tuning nests under `"advanced"`). Only the named leaves change.
 *
 * # Safety
 * `handle` must be a live handle; `overlay_json` must be a valid
 * NUL-terminated C string.
 */
RinggridStatus ringgrid_detector_update_config(RinggridDetector *handle, const char *overlay_json);

/**
 * Free a detector handle. NULL is a no-op.
 *
 * # Safety
 * `handle` must be NULL or a handle returned by a `ringgrid_detector_*`
 * constructor, freed exactly once.
 */
void ringgrid_detector_free(RinggridDetector *handle);

/**
 * ringgrid version as a NUL-terminated string written to `out` (owned; free
 * with `ringgrid_string_free`).
 *
 * # Safety
 * `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_version(char **out);

/**
 * The ABI version of this library. A C++ (or C) consumer compiled against a
 * given header should check this equals the header's `RINGGRID_ABI_VERSION`.
 */
uint32_t ringgrid_abi_version(void);

/**
 * The default coded-hex target as `ringgrid.target.v6` JSON.
 *
 * # Safety
 * `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_default_target_json(char **out);

/**
 * The 24×24 plain-rect target (with origin dots) as `ringgrid.target.v6` JSON.
 *
 * # Safety
 * `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_rect_24x24_target_json(char **out);

/**
 * The default detection config for a target layout, as a JSON string.
 *
 * # Safety
 * `target_json` must be a valid NUL-terminated C string; `out` must point to a
 * writable `char*` slot.
 */
RinggridStatus ringgrid_default_config_json(const char *target_json, char **out);

/**
 * The four-tier-wide scale-tier preset (≈8–220 px) as JSON.
 *
 * # Safety
 * `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_scale_tiers_four_tier_wide_json(char **out);

/**
 * The two-tier-standard scale-tier preset (≈14–100 px) as JSON.
 *
 * # Safety
 * `out` must point to a writable `char*` slot.
 */
RinggridStatus ringgrid_scale_tiers_two_tier_standard_json(char **out);

/**
 * Generate proposals with a heatmap (grayscale). The heatmap is cached; read
 * it with `ringgrid_heatmap_data`. Writes proposals + image size to `out`.
 *
 * # Safety
 * `handle` must be a live handle; `pixels` must point to `width*height` bytes;
 * `out` must be a writable `char*` slot.
 */
RinggridStatus ringgrid_propose_with_heatmap(RinggridDetector *handle,
                                             const uint8_t *pixels,
                                             uint32_t width,
                                             uint32_t height,
                                             char **out);

/**
 * Generate proposals with a heatmap (RGBA, BT.601-converted).
 *
 * # Safety
 * As [`ringgrid_propose_with_heatmap`], but `pixels` must point to
 * `width*height*4` bytes.
 */
RinggridStatus ringgrid_propose_with_heatmap_rgba(RinggridDetector *handle,
                                                  const uint8_t *pixels,
                                                  uint32_t width,
                                                  uint32_t height,
                                                  char **out);

/**
 * Borrow the last heatmap as a `float` buffer of `width*height` values.
 *
 * The pointer written to `out_ptr` is **borrowed** from the handle: it is
 * valid until the next `ringgrid_propose_with_heatmap*` call or
 * `ringgrid_detector_free`, and must **not** be freed. Returns
 * `RINGGRID_STATUS_ERR_NO_HEATMAP` if no proposal call has run yet.
 *
 * # Safety
 * `handle` must be a live handle; `out_ptr` and `out_len` must point to
 * writable slots.
 */
RinggridStatus ringgrid_heatmap_data(const RinggridDetector *handle,
                                     const float **out_ptr,
                                     uintptr_t *out_len);

/**
 * Width of the last heatmap (0 if none, or on NULL handle).
 *
 * # Safety
 * `handle` must be NULL or a live handle.
 */
uint32_t ringgrid_heatmap_width(const RinggridDetector *handle);

/**
 * Height of the last heatmap (0 if none, or on NULL handle).
 *
 * # Safety
 * `handle` must be NULL or a live handle.
 */
uint32_t ringgrid_heatmap_height(const RinggridDetector *handle);

/**
 * Human-readable description of a status code.
 *
 * The returned pointer is a static, NUL-terminated string owned by the
 * library — the caller must **not** free it (unlike the owned strings the
 * other entry points return).
 */
const char *ringgrid_status_str(RinggridStatus status);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RINGGRID_H */
