"""ringgrid Python bindings.

High-level, typed API for dense coded ring marker detection backed by the
native Rust detector.
"""

from ._api import (
    BoardLayout,
    BoardMarker,
    CameraIntrinsics,
    CameraModel,
    CircleRefinementMethod,
    CompletionParams,
    DecodeConfig,
    DecodeMetrics,
    DetectConfig,
    DetectedMarker,
    DetectionFrame,
    DetectionResult,
    Detector,
    DivisionModel,
    EdgeSampleConfig,
    Ellipse,
    FitMetrics,
    IdCorrectionConfig,
    InnerAsOuterRecoveryConfig,
    InnerFitConfig,
    MarkerSpec,
    MarkerScalePrior,
    OuterEstimationConfig,
    OuterFitConfig,
    ProjectiveCenterParams,
    ProposalConfig,
    ScaleTier,
    ScaleTiers,
    RadialTangentialDistortion,
    RansacFitConfig,
    RansacHomographyConfig,
    RansacStats,
    SeedProposalParams,
    SelfUndistortConfig,
    SelfUndistortResult,
    __version__,
)

__all__ = [
    "BoardLayout",
    "BoardMarker",
    "CircleRefinementMethod",
    "MarkerSpec",
    "MarkerScalePrior",
    "RansacFitConfig",
    "InnerFitConfig",
    "OuterFitConfig",
    "CompletionParams",
    "ProjectiveCenterParams",
    "SeedProposalParams",
    "ProposalConfig",
    "EdgeSampleConfig",
    "DecodeConfig",
    "OuterEstimationConfig",
    "RansacHomographyConfig",
    "SelfUndistortConfig",
    "IdCorrectionConfig",
    "InnerAsOuterRecoveryConfig",
    "ScaleTier",
    "ScaleTiers",
    "DetectConfig",
    "Detector",
    "CameraIntrinsics",
    "RadialTangentialDistortion",
    "CameraModel",
    "DivisionModel",
    "DetectionResult",
    "DetectedMarker",
    "FitMetrics",
    "DecodeMetrics",
    "RansacStats",
    "SelfUndistortResult",
    "Ellipse",
    "DetectionFrame",
    "__version__",
]
