#!/usr/bin/env python3
"""Generate canonical parametric board specification JSON.

The target schema is `ringgrid.target.v2` and stores board geometry as
`rows + long_row_cols` plus marker radii. Marker positions are generated by the
Rust runtime from this parametric description.

Usage:
    python tools/gen_board_spec.py
    python tools/gen_board_spec.py --pitch_mm 8.0 --rows 15 --long_row_cols 14
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TARGET_SCHEMA = "ringgrid.target.v2"


def count_markers(rows: int, long_row_cols: int) -> int:
    if rows <= 0:
        raise ValueError("rows must be >= 1")
    if long_row_cols <= 0:
        raise ValueError("long_row_cols must be >= 1")
    if rows > 1 and long_row_cols < 2:
        raise ValueError("long_row_cols must be >= 2 when rows > 1")

    short_row_cols = long_row_cols - 1
    mid = rows // 2
    total = 0
    for row_idx in range(rows):
        r = row_idx - mid
        if rows == 1:
            n_cols = long_row_cols
        elif ((r + long_row_cols - 1) & 1) == 0:
            n_cols = long_row_cols
        else:
            n_cols = short_row_cols
        if n_cols <= 0:
            raise ValueError("derived row has zero columns")
        total += n_cols
    return total


def write_json(path: Path, spec: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(spec, f, indent=2)
        f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate board specification JSON")
    parser.add_argument("--pitch_mm", type=float, default=8.0)
    parser.add_argument("--rows", type=int, default=15)
    parser.add_argument("--long_row_cols", type=int, default=14)
    parser.add_argument("--board_mm", type=float, default=200.0)
    parser.add_argument("--name", type=str, default=None)
    parser.add_argument("--marker_outer_radius_mm", type=float, default=None)
    parser.add_argument("--marker_inner_radius_mm", type=float, default=None)
    parser.add_argument("--marker_code_band_outer_radius_mm", type=float, default=None)
    parser.add_argument("--marker_code_band_inner_radius_mm", type=float, default=None)
    parser.add_argument(
        "--json_out",
        type=str,
        default="tools/board/board_spec.json",
    )
    args = parser.parse_args()

    if args.pitch_mm <= 0:
        raise ValueError("--pitch_mm must be > 0")

    n_markers = count_markers(args.rows, args.long_row_cols)

    outer = (
        args.marker_outer_radius_mm
        if args.marker_outer_radius_mm is not None
        else args.pitch_mm * 0.6
    )
    inner = (
        args.marker_inner_radius_mm
        if args.marker_inner_radius_mm is not None
        else args.pitch_mm * 0.4
    )
    code_outer = (
        args.marker_code_band_outer_radius_mm
        if args.marker_code_band_outer_radius_mm is not None
        else args.pitch_mm * 0.58
    )
    code_inner = (
        args.marker_code_band_inner_radius_mm
        if args.marker_code_band_inner_radius_mm is not None
        else args.pitch_mm * 0.42
    )

    if not (inner > 0 and outer > 0 and inner < outer):
        raise ValueError("marker radii must satisfy 0 < inner < outer")
    if not (code_inner > inner and code_outer > code_inner and code_outer < outer):
        raise ValueError(
            "code-band radii must satisfy inner < code_inner < code_outer < outer"
        )

    name = args.name or f"ringgrid_{int(args.board_mm)}mm_hex"

    spec = {
        "schema": TARGET_SCHEMA,
        "name": name,
        "pitch_mm": float(args.pitch_mm),
        "rows": int(args.rows),
        "long_row_cols": int(args.long_row_cols),
        "marker_outer_radius_mm": float(outer),
        "marker_inner_radius_mm": float(inner),
        "marker_code_band_outer_radius_mm": float(code_outer),
        "marker_code_band_inner_radius_mm": float(code_inner),
    }

    out_path = Path(args.json_out)
    write_json(out_path, spec)

    print(f"Board spec JSON written to {out_path}")
    print(
        f"Board: {name}, schema={TARGET_SCHEMA}, rows={args.rows}, "
        f"long_row_cols={args.long_row_cols}, markers={n_markers}, "
        f"pitch={args.pitch_mm}mm"
    )


if __name__ == "__main__":
    main()
