#!/usr/bin/env python3
"""Generate canonical parametric board specification JSON.

The target schema is `ringgrid.target.v4` and stores board geometry as
`rows + long_row_cols` plus marker radii and ring width. Marker positions are
generated by the Rust runtime from this parametric description.

Usage:
    python tools/gen_board_spec.py
    python tools/gen_board_spec.py --pitch_mm 8.0 --rows 15 --long_row_cols 14
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


TARGET_SCHEMA = "ringgrid.target.v4"
DEFAULT_RING_WIDTH_RATIO = 0.24


def count_markers(rows: int, long_row_cols: int) -> int:
    if rows <= 0:
        raise ValueError("rows must be >= 1")
    if long_row_cols <= 0:
        raise ValueError("long_row_cols must be >= 1")
    if rows > 1 and long_row_cols < 2:
        raise ValueError("long_row_cols must be >= 2 when rows > 1")

    short_row_cols = long_row_cols - 1
    mid = rows // 2
    total = 0
    for row_idx in range(rows):
        r = row_idx - mid
        if rows == 1:
            n_cols = long_row_cols
        elif ((r + long_row_cols - 1) & 1) == 0:
            n_cols = long_row_cols
        else:
            n_cols = short_row_cols
        if n_cols <= 0:
            raise ValueError("derived row has zero columns")
        total += n_cols
    return total


def hex_row_spacing_mm(pitch_mm: float) -> float:
    return pitch_mm * (3.0 ** 0.5)


def marker_ring_half_thickness_mm(marker_ring_width_mm: float) -> float:
    return 0.5 * marker_ring_width_mm


def validate_marker_geometry(
    pitch_mm: float,
    marker_outer_radius_mm: float,
    marker_inner_radius_mm: float,
    marker_ring_width_mm: float,
) -> None:
    if not math.isfinite(pitch_mm) or pitch_mm <= 0:
        raise ValueError("pitch_mm must be finite and > 0")
    if not math.isfinite(marker_outer_radius_mm) or marker_outer_radius_mm <= 0:
        raise ValueError("marker_outer_radius_mm must be finite and > 0")
    if not math.isfinite(marker_inner_radius_mm) or marker_inner_radius_mm <= 0:
        raise ValueError("marker_inner_radius_mm must be finite and > 0")
    if marker_inner_radius_mm >= marker_outer_radius_mm:
        raise ValueError("marker radii must satisfy 0 < inner < outer")
    if not math.isfinite(marker_ring_width_mm) or marker_ring_width_mm <= 0:
        raise ValueError("marker_ring_width_mm must be finite and > 0")

    ring_half_thickness_mm = marker_ring_half_thickness_mm(marker_ring_width_mm)
    inner_ring_outer_edge_mm = marker_inner_radius_mm + ring_half_thickness_mm
    outer_ring_inner_edge_mm = marker_outer_radius_mm - ring_half_thickness_mm
    if inner_ring_outer_edge_mm >= outer_ring_inner_edge_mm:
        raise ValueError(
            "marker geometry leaves no code band between rings "
            f"(inner ring outer edge={inner_ring_outer_edge_mm:.4f}mm, "
            f"outer ring inner edge={outer_ring_inner_edge_mm:.4f}mm)"
        )

    min_center_spacing_mm = hex_row_spacing_mm(pitch_mm)
    marker_outer_diameter_mm = 2.0 * marker_outer_radius_mm
    if marker_outer_diameter_mm >= min_center_spacing_mm:
        raise ValueError(
            "marker outer diameter "
            f"({marker_outer_diameter_mm:.4f}mm) must be smaller than minimum "
            f"center spacing ({min_center_spacing_mm:.4f}mm)"
        )

    marker_draw_diameter_mm = 2.0 * (marker_outer_radius_mm + ring_half_thickness_mm)
    if marker_draw_diameter_mm >= min_center_spacing_mm:
        raise ValueError(
            "printed marker diameter including ring stroke "
            f"({marker_draw_diameter_mm:.4f}mm) must be smaller than minimum "
            f"center spacing ({min_center_spacing_mm:.4f}mm)"
        )


def write_json(path: Path, spec: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(spec, f, indent=2)
        f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate board specification JSON")
    parser.add_argument("--pitch_mm", type=float, default=8.0)
    parser.add_argument("--rows", type=int, default=15)
    parser.add_argument("--long_row_cols", type=int, default=14)
    parser.add_argument("--board_mm", type=float, default=200.0)
    parser.add_argument("--name", type=str, default=None)
    parser.add_argument("--marker_outer_radius_mm", type=float, default=None)
    parser.add_argument("--marker_inner_radius_mm", type=float, default=None)
    parser.add_argument("--marker_ring_width_mm", type=float, default=None)
    parser.add_argument("--json_out", type=str, default="tools/board/board_spec.json")
    args = parser.parse_args()

    n_markers = count_markers(args.rows, args.long_row_cols)

    outer = (
        args.marker_outer_radius_mm
        if args.marker_outer_radius_mm is not None
        else args.pitch_mm * 0.6
    )
    inner = (
        args.marker_inner_radius_mm
        if args.marker_inner_radius_mm is not None
        else args.pitch_mm * 0.4
    )
    ring_width = (
        args.marker_ring_width_mm
        if args.marker_ring_width_mm is not None
        else outer * DEFAULT_RING_WIDTH_RATIO
    )
    validate_marker_geometry(args.pitch_mm, outer, inner, ring_width)

    name = args.name or f"ringgrid_{int(args.board_mm)}mm_hex"

    spec = {
        "schema": TARGET_SCHEMA,
        "name": name,
        "pitch_mm": float(args.pitch_mm),
        "rows": int(args.rows),
        "long_row_cols": int(args.long_row_cols),
        "marker_outer_radius_mm": float(outer),
        "marker_inner_radius_mm": float(inner),
        "marker_ring_width_mm": float(ring_width),
    }

    out_path = Path(args.json_out)
    write_json(out_path, spec)

    print(f"Board spec JSON written to {out_path}")
    print(
        f"Board: {name}, schema={TARGET_SCHEMA}, rows={args.rows}, "
        f"long_row_cols={args.long_row_cols}, markers={n_markers}, "
        f"pitch={args.pitch_mm}mm"
    )


if __name__ == "__main__":
    main()
